lecteurcarte.o: lecteurcarte.cpp lecteurcarte.h BaseClients.h voyants.h \
 timer.h recharge.h
borne.o: borne.cpp lecteurcarte.h BaseClients.h voyants.h timer.h
BaseClients.o: BaseClients.cpp BaseClients.h
timer.o: timer.cpp timer.h
voyants.o: voyants.cpp voyants.h timer.h
recharge.o: recharge.cpp timer.h recharge.h voyants.h
